# Generated by Django 5.2.8 on 2025-12-19 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='회사명')),
                ('name_en', models.CharField(blank=True, help_text='회사명 영문', max_length=200, verbose_name='회사명(영문)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사들',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_compan_name_f8e523_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(blank=True, help_text='사용자가 소속된 회사', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.company', verbose_name='소속 회사')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
                'indexes': [models.Index(fields=['company'], name='core_userpr_company_63fd69_idx')],
            },
        ),
    ]
