# Generated by Django 5.2.8 on 2025-11-18 08:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0002_alter_performance_crew'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='공연 날짜')),
                ('booking_site', models.CharField(max_length=100, verbose_name='예매처')),
                ('paid_revenue', models.DecimalField(decimal_places=0, help_text='예매처별(입금) 판매액', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='입금 판매액 (원)')),
                ('paid_ticket_count', models.IntegerField(help_text='예매처별(입금) 판매 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='입금 판매 매수')),
                ('paid_by_grade', models.JSONField(blank=True, default=dict, help_text='예매처별(입금) 등급별 판매 매수 (예: {"VIP": 5, "R석": 10})', verbose_name='입금 등급별 판매 매수')),
                ('unpaid_revenue', models.DecimalField(decimal_places=0, default=0, help_text='예매처별(미입금) 판매액', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='미입금 판매액 (원)')),
                ('unpaid_ticket_count', models.IntegerField(default=0, help_text='예매처별(미입금) 판매 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='미입금 판매 매수')),
                ('unpaid_by_grade', models.JSONField(blank=True, default=dict, help_text='예매처별(미입금) 등급별 판매 매수 (예: {"VIP": 2, "R석": 3})', verbose_name='미입금 등급별 판매 매수')),
                ('free_by_grade', models.JSONField(blank=True, default=dict, help_text='예매처별 등급별 초대 매수 (예: {"VIP": 1, "R석": 2})', verbose_name='등급별 초대 매수')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('performance', models.ForeignKey(limit_choices_to={'genre': 'concert'}, on_delete=django.db.models.deletion.CASCADE, related_name='concert_sales', to='performance.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '콘서트 매출',
                'verbose_name_plural': '콘서트 매출',
                'ordering': ['-date', 'performance', 'booking_site'],
                'indexes': [models.Index(fields=['performance', 'date'], name='data_manage_perform_71e4ae_idx'), models.Index(fields=['date'], name='data_manage_date_fc5bb1_idx'), models.Index(fields=['booking_site'], name='data_manage_booking_b88a3d_idx')],
                'unique_together': {('performance', 'date', 'booking_site')},
            },
        ),
    ]
