# Generated by Django 5.2.8 on 2025-11-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
        ('performance', '0002_alter_performance_crew'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='concertsales',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='concertsales',
            name='sales_type',
            field=models.CharField(choices=[('daily', '데일리'), ('final', '최종')], default='daily', help_text='데일리 매출 또는 최종 매출', max_length=10, verbose_name='매출 타입'),
        ),
        migrations.AlterUniqueTogether(
            name='concertsales',
            unique_together={('performance', 'date', 'booking_site', 'sales_type')},
        ),
    ]
