# Generated by Django 5.2.8 on 2025-11-19 06:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_sales_data(apps, schema_editor):
    """기존 ConcertSales 데이터를 ConcertDailySales와 ConcertFinalSales로 마이그레이션"""
    ConcertSales = apps.get_model('data_management', 'ConcertSales')
    ConcertDailySales = apps.get_model('data_management', 'ConcertDailySales')
    ConcertFinalSales = apps.get_model('data_management', 'ConcertFinalSales')
    
    # 기존 데이터 마이그레이션
    for sales in ConcertSales.objects.all():
        if sales.sales_type == 'daily':
            # 데일리 매출 데이터
            ConcertDailySales.objects.create(
                performance=sales.performance,
                date=sales.date,
                booking_site=sales.booking_site,
                paid_revenue=sales.paid_revenue,
                paid_ticket_count=sales.paid_ticket_count,
                paid_by_grade=sales.paid_by_grade,
                unpaid_revenue=sales.unpaid_revenue,
                unpaid_ticket_count=sales.unpaid_ticket_count,
                unpaid_by_grade=sales.unpaid_by_grade,
                free_by_grade=sales.free_by_grade,
                notes=sales.notes,
                created_at=sales.created_at,
                updated_at=sales.updated_at,
            )
        elif sales.sales_type == 'final':
            # 최종 매출 데이터
            ConcertFinalSales.objects.create(
                performance=sales.performance,
                booking_site=sales.booking_site,
                paid_revenue=sales.paid_revenue,
                paid_ticket_count=sales.paid_ticket_count,
                paid_by_grade=sales.paid_by_grade,
                unpaid_revenue=sales.unpaid_revenue,
                unpaid_ticket_count=sales.unpaid_ticket_count,
                unpaid_by_grade=sales.unpaid_by_grade,
                free_by_grade=sales.free_by_grade,
                notes=sales.notes,
                created_at=sales.created_at,
                updated_at=sales.updated_at,
            )


def reverse_migrate_sales_data(apps, schema_editor):
    """역방향 마이그레이션 (롤백용)"""
    ConcertSales = apps.get_model('data_management', 'ConcertSales')
    ConcertDailySales = apps.get_model('data_management', 'ConcertDailySales')
    ConcertFinalSales = apps.get_model('data_management', 'ConcertFinalSales')
    
    # ConcertDailySales 데이터를 ConcertSales로 복원
    for daily_sales in ConcertDailySales.objects.all():
        ConcertSales.objects.create(
            performance=daily_sales.performance,
            sales_type='daily',
            date=daily_sales.date,
            booking_site=daily_sales.booking_site,
            paid_revenue=daily_sales.paid_revenue,
            paid_ticket_count=daily_sales.paid_ticket_count,
            paid_by_grade=daily_sales.paid_by_grade,
            unpaid_revenue=daily_sales.unpaid_revenue,
            unpaid_ticket_count=daily_sales.unpaid_ticket_count,
            unpaid_by_grade=daily_sales.unpaid_by_grade,
            free_by_grade=daily_sales.free_by_grade,
            notes=daily_sales.notes,
            created_at=daily_sales.created_at,
            updated_at=daily_sales.updated_at,
        )
    
    # ConcertFinalSales 데이터를 ConcertSales로 복원
    for final_sales in ConcertFinalSales.objects.all():
        ConcertSales.objects.create(
            performance=final_sales.performance,
            sales_type='final',
            date=final_sales.performance.performance_end if final_sales.performance else None,
            booking_site=final_sales.booking_site,
            paid_revenue=final_sales.paid_revenue,
            paid_ticket_count=final_sales.paid_ticket_count,
            paid_by_grade=final_sales.paid_by_grade,
            unpaid_revenue=final_sales.unpaid_revenue,
            unpaid_ticket_count=final_sales.unpaid_ticket_count,
            unpaid_by_grade=final_sales.unpaid_by_grade,
            free_by_grade=final_sales.free_by_grade,
            notes=final_sales.notes,
            created_at=final_sales.created_at,
            updated_at=final_sales.updated_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_alter_concertsales_unique_together_and_more'),
        ('performance', '0003_performance_break_even_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertDailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='공연 날짜')),
                ('booking_site', models.CharField(max_length=100, verbose_name='예매처')),
                ('paid_revenue', models.DecimalField(decimal_places=0, help_text='예매처별(입금) 판매액', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='입금 판매액 (원)')),
                ('paid_ticket_count', models.IntegerField(help_text='예매처별(입금) 판매 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='입금 판매 매수')),
                ('paid_by_grade', models.JSONField(blank=True, default=dict, help_text='예매처별(입금) 등급별 판매 매수 (예: {"VIP": 5, "R석": 10})', verbose_name='입금 등급별 판매 매수')),
                ('unpaid_revenue', models.DecimalField(decimal_places=0, default=0, help_text='예매처별(미입금) 판매액', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='미입금 판매액 (원)')),
                ('unpaid_ticket_count', models.IntegerField(default=0, help_text='예매처별(미입금) 판매 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='미입금 판매 매수')),
                ('unpaid_by_grade', models.JSONField(blank=True, default=dict, help_text='예매처별(미입금) 등급별 판매 매수 (예: {"VIP": 2, "R석": 3})', verbose_name='미입금 등급별 판매 매수')),
                ('free_by_grade', models.JSONField(blank=True, default=dict, help_text='예매처별 등급별 초대 매수 (예: {"VIP": 1, "R석": 2})', verbose_name='등급별 초대 매수')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('performance', models.ForeignKey(limit_choices_to={'genre': 'concert'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='performance.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '콘서트 데일리 매출',
                'verbose_name_plural': '콘서트 데일리 매출',
                'ordering': ['-date', 'performance', 'booking_site'],
            },
        ),
        migrations.CreateModel(
            name='ConcertFinalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_site', models.CharField(max_length=100, verbose_name='예매처')),
                ('paid_revenue', models.DecimalField(decimal_places=0, help_text='예매처별(입금) 판매액', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='입금 판매액 (원)')),
                ('paid_ticket_count', models.IntegerField(help_text='예매처별(입금) 판매 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='입금 판매 매수')),
                ('paid_by_grade', models.JSONField(blank=True, default=dict, help_text='예매처별(입금) 등급별 판매 매수 (예: {"VIP": 5, "R석": 10})', verbose_name='입금 등급별 판매 매수')),
                ('unpaid_revenue', models.DecimalField(decimal_places=0, default=0, help_text='예매처별(미입금) 판매액', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='미입금 판매액 (원)')),
                ('unpaid_ticket_count', models.IntegerField(default=0, help_text='예매처별(미입금) 판매 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='미입금 판매 매수')),
                ('unpaid_by_grade', models.JSONField(blank=True, default=dict, help_text='예매처별(미입금) 등급별 판매 매수 (예: {"VIP": 2, "R석": 3})', verbose_name='미입금 등급별 판매 매수')),
                ('free_by_grade', models.JSONField(blank=True, default=dict, help_text='예매처별 등급별 초대 매수 (예: {"VIP": 1, "R석": 2})', verbose_name='등급별 초대 매수')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('performance', models.ForeignKey(limit_choices_to={'genre': 'concert'}, on_delete=django.db.models.deletion.CASCADE, related_name='final_sales', to='performance.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '콘서트 최종 매출',
                'verbose_name_plural': '콘서트 최종 매출',
                'ordering': ['performance', 'booking_site'],
            },
        ),
        migrations.RunPython(migrate_sales_data, reverse_migrate_sales_data),
        migrations.DeleteModel(
            name='ConcertSales',
        ),
        migrations.AddIndex(
            model_name='concertdailysales',
            index=models.Index(fields=['performance', 'date'], name='data_manage_perform_8e5a35_idx'),
        ),
        migrations.AddIndex(
            model_name='concertdailysales',
            index=models.Index(fields=['date'], name='data_manage_date_81c73d_idx'),
        ),
        migrations.AddIndex(
            model_name='concertdailysales',
            index=models.Index(fields=['booking_site'], name='data_manage_booking_e8bbcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='concertdailysales',
            unique_together={('performance', 'date', 'booking_site')},
        ),
        migrations.AddIndex(
            model_name='concertfinalsales',
            index=models.Index(fields=['performance'], name='data_manage_perform_92c73a_idx'),
        ),
        migrations.AddIndex(
            model_name='concertfinalsales',
            index=models.Index(fields=['booking_site'], name='data_manage_booking_d6f0f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='concertfinalsales',
            unique_together={('performance', 'booking_site')},
        ),
    ]
