# Generated by Django 5.2.8 on 2025-11-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_concertdailysales_concertfinalsales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertfinalsales',
            name='age_gender_sales',
            field=models.JSONField(blank=True, default=list, help_text='연령대별, 성별별 판매 매수 (예: [{"age_group": "21 ~ 30", "male_count": 100, "female_count": 120, "unknown_count": 10, "total_count": 230}])', verbose_name='연령대별 성별 판매현황'),
        ),
        migrations.AddField(
            model_name='concertfinalsales',
            name='booking_site_discount_sales',
            field=models.JSONField(blank=True, default=dict, help_text='예매처별 할인권종별 판매 정보 (예: {"인터파크": [{"discount_type": "조조할인", "sales_count": 50, "revenue": 5000000}]})', verbose_name='예매처별 할인권종별 판매현황'),
        ),
        migrations.AddField(
            model_name='concertfinalsales',
            name='card_sales_summary',
            field=models.JSONField(blank=True, default=list, help_text='카드 종류별 매수 및 금액 (예: [{"card_type": "삼성카드", "count": 200, "amount": 20000000}])', verbose_name='카드별 매출집계'),
        ),
        migrations.AddField(
            model_name='concertfinalsales',
            name='grade_sales_summary',
            field=models.JSONField(blank=True, default=dict, help_text='관람 등급별 판매 정보 (예: {"VIP": {"paid_count": 100, "free_count": 10, "revenue": 15000000, "paid_occupancy_rate": 0.85, "total_occupancy_rate": 0.92, "total_count": 110}})', verbose_name='예매처 통합 등급별 판매현황'),
        ),
        migrations.AddField(
            model_name='concertfinalsales',
            name='gyeonggi_region_sales',
            field=models.JSONField(blank=True, default=list, help_text='경기 지역별 매수 (예: [{"region": "수원시", "count": 50}])', verbose_name='경기 지역별 판매현황'),
        ),
        migrations.AddField(
            model_name='concertfinalsales',
            name='payment_method_sales',
            field=models.JSONField(blank=True, default=list, help_text='결제수단별 매수 및 금액 (예: [{"payment_method": "신용카드", "count": 500, "amount": 50000000}])', verbose_name='결제수단별 판매현황'),
        ),
        migrations.AddField(
            model_name='concertfinalsales',
            name='region_sales',
            field=models.JSONField(blank=True, default=list, help_text='지역별 매수 (예: [{"region": "서울", "count": 400}])', verbose_name='지역별 판매현황'),
        ),
        migrations.AddField(
            model_name='concertfinalsales',
            name='sales_channel_sales',
            field=models.JSONField(blank=True, default=list, help_text='판매경로별 매수 및 금액 (예: [{"sales_channel": "온라인", "count": 600, "amount": 60000000}])', verbose_name='판매경로별 판매현황'),
        ),
        migrations.AddField(
            model_name='concertfinalsales',
            name='seoul_region_sales',
            field=models.JSONField(blank=True, default=list, help_text='서울 지역별 매수 (예: [{"region": "강남구", "count": 100}])', verbose_name='서울 지역별 판매현황'),
        ),
    ]
