# Generated by Django 5.2.8 on 2025-12-19 02:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def delete_existing_sales_data(apps, schema_editor):
    """기존 매출 데이터 삭제 (기존 데이터가 없으므로 삭제)"""
    ConcertDailySales = apps.get_model('data_management', 'ConcertDailySales')
    ConcertFinalSales = apps.get_model('data_management', 'ConcertFinalSales')
    
    ConcertDailySales.objects.all().delete()
    ConcertFinalSales.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_concertfinalsales_age_gender_sales_and_more'),
        ('performance', '0009_remove_performance_booking_sites_and_more'),
    ]

    operations = [
        # 기존 데이터 삭제 (CharField -> ForeignKey 변환 전)
        migrations.RunPython(
            code=delete_existing_sales_data,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='ConcertDailySalesGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_count', models.IntegerField(default=0, help_text='해당 등급의 입금 판매 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='입금 판매 매수')),
                ('unpaid_count', models.IntegerField(default=0, help_text='해당 등급의 미입금 판매 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='미입금 판매 매수')),
                ('free_count', models.IntegerField(default=0, help_text='해당 등급의 무료(초대) 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='무료 매수')),
            ],
            options={
                'verbose_name': '콘서트 데일리 등급별 판매',
                'verbose_name_plural': '콘서트 데일리 등급별 판매들',
                'ordering': ['daily_sales', 'seat_grade__order'],
            },
        ),
        migrations.CreateModel(
            name='ConcertFinalSalesGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_count', models.IntegerField(default=0, help_text='해당 등급의 입금 판매 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='입금 판매 매수')),
                ('unpaid_count', models.IntegerField(default=0, help_text='해당 등급의 미입금 판매 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='미입금 판매 매수')),
                ('free_count', models.IntegerField(default=0, help_text='해당 등급의 무료(초대) 매수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='무료 매수')),
                ('paid_revenue', models.DecimalField(decimal_places=0, default=0, help_text='해당 등급의 입금 매출액', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='입금 매출액 (원)')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, help_text='해당 등급의 총 매출액 (입금 + 미입금)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 매출액 (원)')),
                ('paid_occupancy_rate', models.DecimalField(blank=True, decimal_places=4, help_text='입금 판매 매수 / 총 좌석 수', max_digits=5, null=True, verbose_name='입금 점유율')),
                ('total_occupancy_rate', models.DecimalField(blank=True, decimal_places=4, help_text='(입금 + 미입금 + 무료) 매수 / 총 좌석 수', max_digits=5, null=True, verbose_name='총 점유율')),
            ],
            options={
                'verbose_name': '콘서트 최종 등급별 판매',
                'verbose_name_plural': '콘서트 최종 등급별 판매들',
                'ordering': ['final_sales', 'seat_grade__order'],
            },
        ),
        migrations.RenameIndex(
            model_name='concertdailysales',
            new_name='data_manage_booking_1ecac8_idx',
            old_name='data_manage_booking_e8bbcb_idx',
        ),
        migrations.RenameIndex(
            model_name='concertfinalsales',
            new_name='data_manage_booking_1b2ea1_idx',
            old_name='data_manage_booking_d6f0f2_idx',
        ),
        migrations.RemoveField(
            model_name='concertdailysales',
            name='free_by_grade',
        ),
        migrations.RemoveField(
            model_name='concertdailysales',
            name='paid_by_grade',
        ),
        migrations.RemoveField(
            model_name='concertdailysales',
            name='unpaid_by_grade',
        ),
        migrations.RemoveField(
            model_name='concertfinalsales',
            name='free_by_grade',
        ),
        migrations.RemoveField(
            model_name='concertfinalsales',
            name='paid_by_grade',
        ),
        migrations.RemoveField(
            model_name='concertfinalsales',
            name='unpaid_by_grade',
        ),
        migrations.AlterField(
            model_name='concertdailysales',
            name='booking_site',
            field=models.ForeignKey(blank=True, help_text='예매처', null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.bookingsite', verbose_name='예매처'),
        ),
        migrations.AlterField(
            model_name='concertfinalsales',
            name='booking_site',
            field=models.ForeignKey(blank=True, help_text='예매처', null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.bookingsite', verbose_name='예매처'),
        ),
        migrations.AddField(
            model_name='concertdailysalesgrade',
            name='daily_sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_sales', to='data_management.concertdailysales', verbose_name='일별 매출'),
        ),
        migrations.AddField(
            model_name='concertdailysalesgrade',
            name='seat_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.seatgrade', verbose_name='좌석 등급'),
        ),
        migrations.AddField(
            model_name='concertfinalsalesgrade',
            name='final_sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_sales', to='data_management.concertfinalsales', verbose_name='최종 매출'),
        ),
        migrations.AddField(
            model_name='concertfinalsalesgrade',
            name='seat_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.seatgrade', verbose_name='좌석 등급'),
        ),
        migrations.AddIndex(
            model_name='concertdailysalesgrade',
            index=models.Index(fields=['daily_sales', 'seat_grade'], name='data_manage_daily_s_ab6f5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='concertdailysalesgrade',
            unique_together={('daily_sales', 'seat_grade')},
        ),
        migrations.AddIndex(
            model_name='concertfinalsalesgrade',
            index=models.Index(fields=['final_sales', 'seat_grade'], name='data_manage_final_s_6b55da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='concertfinalsalesgrade',
            unique_together={('final_sales', 'seat_grade')},
        ),
    ]
