# Generated by Django 5.2.8 on 2026-02-03 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_rename_concert_sales_models'),
        ('performance', '0015_remove_artist_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancedailysales',
            options={'ordering': ['-date', 'performance', 'booking_site'], 'verbose_name': '공연 데일리 매출', 'verbose_name_plural': '공연 데일리 매출'},
        ),
        migrations.AlterModelOptions(
            name='performancedailysalesgrade',
            options={'ordering': ['daily_sales', 'seat_grade__order'], 'verbose_name': '공연 데일리 등급별 판매', 'verbose_name_plural': '공연 데일리 등급별 판매들'},
        ),
        migrations.AlterModelOptions(
            name='performancefinalsales',
            options={'ordering': ['performance', 'booking_site'], 'verbose_name': '공연 최종 매출', 'verbose_name_plural': '공연 최종 매출'},
        ),
        migrations.AlterModelOptions(
            name='performancefinalsalesgrade',
            options={'ordering': ['final_sales', 'seat_grade__order'], 'verbose_name': '공연 최종 등급별 판매', 'verbose_name_plural': '공연 최종 등급별 판매들'},
        ),
        migrations.RenameIndex(
            model_name='performancedailysales',
            new_name='data_manage_perform_46936f_idx',
            old_name='data_manage_perform_8e5a35_idx',
        ),
        migrations.RenameIndex(
            model_name='performancedailysales',
            new_name='data_manage_date_cf76e6_idx',
            old_name='data_manage_date_81c73d_idx',
        ),
        migrations.RenameIndex(
            model_name='performancedailysales',
            new_name='data_manage_booking_fbf02b_idx',
            old_name='data_manage_booking_1ecac8_idx',
        ),
        migrations.RenameIndex(
            model_name='performancedailysalesgrade',
            new_name='data_manage_daily_s_ee253e_idx',
            old_name='data_manage_daily_s_ab6f5d_idx',
        ),
        migrations.RenameIndex(
            model_name='performancefinalsales',
            new_name='data_manage_perform_dee683_idx',
            old_name='data_manage_perform_92c73a_idx',
        ),
        migrations.RenameIndex(
            model_name='performancefinalsales',
            new_name='data_manage_booking_c3a604_idx',
            old_name='data_manage_booking_1b2ea1_idx',
        ),
        migrations.RenameIndex(
            model_name='performancefinalsalesgrade',
            new_name='data_manage_final_s_ddf7fa_idx',
            old_name='data_manage_final_s_6b55da_idx',
        ),
        migrations.AlterField(
            model_name='performancedailysales',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='performance.performance', verbose_name='공연'),
        ),
        migrations.AlterField(
            model_name='performancefinalsales',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_sales', to='performance.performance', verbose_name='공연'),
        ),
    ]
