# Generated by Django 5.2.8 on 2026-02-04 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_alter_performancedailysales_options_and_more'),
        ('performance', '0015_remove_artist_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSalesUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='파일명')),
                ('sheet_name', models.CharField(blank=True, max_length=100, verbose_name='시트명')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='데이터 시작일')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='데이터 종료일')),
                ('daily_sales_count', models.IntegerField(default=0, verbose_name='일별 매출 건수')),
                ('grade_sales_count', models.IntegerField(default=0, verbose_name='등급별 매출 건수')),
                ('status', models.CharField(choices=[('success', '성공'), ('failed', '실패')], default='success', max_length=20, verbose_name='상태')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='메시지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_upload_logs', to='performance.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '공연 매출 업로드 기록',
                'verbose_name_plural': '공연 매출 업로드 기록',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['performance', 'uploaded_at'], name='data_manage_perform_798807_idx')],
            },
        ),
    ]
