# Generated by Django 5.2.8 on 2026-02-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0012_performancesalesuploadactionlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='performancesalesuploadactionlog',
            new_name='data_manage_perform_f51d47_idx',
            old_name='data_manage_perform_2fd4b0_idx',
        ),
        migrations.RenameIndex(
            model_name='performancesalesuploadactionlog',
            new_name='data_manage_action__23a797_idx',
            old_name='data_manage_action__2c8395_idx',
        ),
    ]
