# Generated by Django 5.2.8 on 2026-03-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0014_musicalepisodesales'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='musicalepisodesales',
            new_name='data_manage_perform_95b75a_idx',
            old_name='data_manage_perform_34f568_idx',
        ),
        migrations.RenameIndex(
            model_name='musicalepisodesales',
            new_name='data_manage_perform_4c7eac_idx',
            old_name='data_manage_perform_734cb0_idx',
        ),
        migrations.RenameIndex(
            model_name='musicalepisodesales',
            new_name='data_manage_upload__08dc68_idx',
            old_name='data_manage_upload__5783a3_idx',
        ),
    ]
