# Generated by Django 5.2.8 on 2025-11-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공연명')),
                ('genre', models.CharField(choices=[('theater', '연극'), ('musical', '뮤지컬'), ('concert', '콘서트'), ('exhibition', '전시')], max_length=20, verbose_name='장르')),
                ('venue', models.CharField(max_length=200, verbose_name='공연장')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='공연명(영문)')),
                ('age_rating', models.CharField(blank=True, max_length=50, verbose_name='관람 연령')),
                ('running_time', models.CharField(blank=True, max_length=50, verbose_name='러닝 타임')),
                ('producer', models.CharField(blank=True, max_length=200, verbose_name='제작/주최')),
                ('organizer', models.CharField(blank=True, max_length=200, verbose_name='주관')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('performance_start', models.DateField(verbose_name='공연 시작일')),
                ('performance_end', models.DateField(verbose_name='공연 종료일')),
                ('sales_start', models.DateField(verbose_name='판매 시작일')),
                ('sales_end', models.DateField(verbose_name='판매 종료일')),
                ('seat_grades', models.JSONField(blank=True, default=list, verbose_name='좌석 등급')),
                ('crew', models.JSONField(blank=True, default=list, verbose_name='제작진')),
                ('booking_sites', models.JSONField(blank=True, default=list, verbose_name='예매처')),
                ('ticket_prices', models.JSONField(blank=True, default=dict, verbose_name='티켓 가격')),
                ('seat_counts', models.JSONField(blank=True, default=dict, verbose_name='좌석 수')),
                ('discounts', models.JSONField(blank=True, default=dict, verbose_name='할인율')),
                ('casting', models.JSONField(blank=True, default=dict, verbose_name='캐스팅')),
                ('seat_map', models.ImageField(blank=True, null=True, upload_to='seat_maps/', verbose_name='좌석배치도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '공연',
                'verbose_name_plural': '공연들',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['genre'], name='performance_genre_c6b847_idx'), models.Index(fields=['performance_start', 'performance_end'], name='performance_perform_570e02_idx')],
            },
        ),
    ]
