# Generated by Django 5.2.8 on 2025-11-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='crew',
            field=models.JSONField(blank=True, default=dict, verbose_name='제작진'),
        ),
    ]
