# Generated by Django 5.2.8 on 2025-11-19 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_alter_performance_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='break_even_point',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='손익분기점 매출액', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='손익분기점 (원)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='target_revenue',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='공연의 목표 매출액', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='목표 금액 (원)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='total_production_cost',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='총 제작비용', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 제작비 (원)'),
        ),
    ]
