# Generated by Django 5.2.8 on 2025-11-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_performance_break_even_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='discount_types',
            field=models.JSONField(blank=True, default=list, verbose_name='할인권종'),
        ),
    ]
