# Generated by Django 5.2.8 on 2025-11-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_performance_discount_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='discounts',
        ),
    ]
