# Generated by Django 5.2.8 on 2025-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_remove_performance_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='도로명 주소'),
        ),
        migrations.AddField(
            model_name='performance',
            name='detail_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='상세 주소'),
        ),
        migrations.AddField(
            model_name='performance',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='우편번호'),
        ),
    ]
