# Generated by Django 5.2.8 on 2025-11-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_performance_address_performance_detail_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='detail_address',
        ),
        migrations.AlterField(
            model_name='performance',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='공연장 주소'),
        ),
    ]
