# Generated by Django 5.2.8 on 2025-12-19 02:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_alter_performance_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='booking_sites',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='discount_types',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='seat_counts',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='seat_grades',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='ticket_prices',
        ),
        migrations.CreateModel(
            name='SeatGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: VIP, R석, S석', max_length=50, verbose_name='등급명')),
                ('price', models.DecimalField(decimal_places=0, help_text='해당 등급의 티켓 가격', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='티켓 가격 (원)')),
                ('seat_count', models.IntegerField(help_text='해당 등급의 총 좌석 수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='좌석 수')),
                ('order', models.IntegerField(default=0, help_text='등급 표시 순서 (작을수록 먼저 표시)', verbose_name='정렬 순서')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_grades', to='performance.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '좌석 등급',
                'verbose_name_plural': '좌석 등급들',
                'ordering': ['performance', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 조조할인, 조기예매할인', max_length=100, verbose_name='할인권종명')),
                ('start_date', models.DateField(verbose_name='할인 시작일')),
                ('end_date', models.DateField(verbose_name='할인 종료일')),
                ('discount_rate', models.IntegerField(help_text='할인 비율 (예: 10 = 10% 할인)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인율 (%)')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_types', to='performance.performance', verbose_name='공연')),
                ('applicable_grades', models.ManyToManyField(blank=True, help_text='이 할인을 적용할 수 있는 좌석 등급들', related_name='applicable_discount_types', to='performance.seatgrade', verbose_name='적용 가능한 등급')),
            ],
            options={
                'verbose_name': '할인권종',
                'verbose_name_plural': '할인권종들',
                'ordering': ['performance', 'start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 인터파크, 예스24', max_length=100, verbose_name='예매처명')),
                ('url', models.URLField(blank=True, help_text='해당 예매처의 예매 페이지 URL', max_length=500, verbose_name='예매 URL')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_sites', to='performance.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '예매처',
                'verbose_name_plural': '예매처들',
                'ordering': ['performance', 'name'],
                'indexes': [models.Index(fields=['performance', 'name'], name='performance_perform_021f62_idx')],
                'unique_together': {('performance', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='seatgrade',
            index=models.Index(fields=['performance', 'order'], name='performance_perform_e0c527_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seatgrade',
            unique_together={('performance', 'name')},
        ),
        migrations.AddIndex(
            model_name='discounttype',
            index=models.Index(fields=['performance', 'start_date', 'end_date'], name='performance_perform_5f9071_idx'),
        ),
    ]
