# Generated by Django 5.2.8 on 2025-12-19 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_remove_performance_booking_sites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='casting',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='crew',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='인물 이름', max_length=200, verbose_name='이름')),
                ('name_en', models.CharField(blank=True, help_text='인물 이름 영문', max_length=200, verbose_name='이름(영문)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '인물',
                'verbose_name_plural': '인물들',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='performance_name_bc961b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrewRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='예: 감독, 음악, 작사, 작곡 등', max_length=100, verbose_name='역할')),
                ('order', models.IntegerField(default=0, help_text='역할 표시 순서 (작을수록 먼저 표시)', verbose_name='정렬 순서')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_roles', to='performance.performance', verbose_name='공연')),
                ('person', models.ForeignKey(help_text='제작진 인물', on_delete=django.db.models.deletion.CASCADE, to='performance.person', verbose_name='인물')),
            ],
            options={
                'verbose_name': '제작진 역할',
                'verbose_name_plural': '제작진 역할들',
                'ordering': ['performance', 'order', 'role'],
                'indexes': [models.Index(fields=['performance', 'order'], name='performance_perform_d178db_idx'), models.Index(fields=['person'], name='performance_person__e00545_idx')],
                'unique_together': {('performance', 'person', 'role')},
            },
        ),
        migrations.CreateModel(
            name='CastingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='예: 홍길동, 김철수 등 배역명', max_length=100, verbose_name='역할')),
                ('order', models.IntegerField(default=0, help_text='역할 표시 순서 (작을수록 먼저 표시)', verbose_name='정렬 순서')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_roles', to='performance.performance', verbose_name='공연')),
                ('person', models.ForeignKey(help_text='배우 인물', on_delete=django.db.models.deletion.CASCADE, to='performance.person', verbose_name='인물')),
            ],
            options={
                'verbose_name': '캐스팅 역할',
                'verbose_name_plural': '캐스팅 역할들',
                'ordering': ['performance', 'order', 'role'],
                'indexes': [models.Index(fields=['performance', 'order'], name='performance_perform_842844_idx'), models.Index(fields=['person'], name='performance_person__bd5ca5_idx')],
                'unique_together': {('performance', 'person', 'role')},
            },
        ),
    ]
