# Generated by Django 5.2.8 on 2025-12-19 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('performance', '0010_remove_performance_casting_remove_performance_crew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='company',
            field=models.ForeignKey(blank=True, help_text='공연을 소유한 회사', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.company', verbose_name='회사'),
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(blank=True, help_text='인물이 소속된 회사', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.company', verbose_name='회사'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['company'], name='performance_company_bca67b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['company'], name='performance_company_c6996b_idx'),
        ),
    ]
