# Generated by Django 5.2.8 on 2025-12-19 10:32

import django.db.models.deletion
from django.db import migrations, models


def ensure_company_assigned(apps, schema_editor):
    """null 값이 있는 경우 기본 회사 할당"""
    Company = apps.get_model('core', 'Company')
    Performance = apps.get_model('performance', 'Performance')
    Person = apps.get_model('performance', 'Person')
    
    # 기본 회사 가져오기 (이미 생성되어 있어야 함)
    try:
        default_company = Company.objects.get(name='라이브러리컴퍼니')
    except Company.DoesNotExist:
        # 없으면 생성
        default_company = Company.objects.create(
            name='라이브러리컴퍼니',
            name_en='Library Company'
        )
    
    # null 값이 있는 Performance에 기본 회사 할당
    Performance.objects.filter(company__isnull=True).update(company=default_company)
    
    # null 값이 있는 Person에 기본 회사 할당
    Person.objects.filter(company__isnull=True).update(company=default_company)


def reverse_ensure_company_assigned(apps, schema_editor):
    """역방향 마이그레이션 (필요시)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assign_default_company'),
        ('performance', '0011_performance_company_person_company_and_more'),
    ]

    operations = [
        # 먼저 null 값이 있는 경우 기본 회사 할당
        migrations.RunPython(ensure_company_assigned, reverse_ensure_company_assigned),
        # 그 다음 null=False로 변경
        migrations.AlterField(
            model_name='performance',
            name='company',
            field=models.ForeignKey(help_text='공연을 소유한 회사', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.company', verbose_name='회사'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(help_text='인물이 소속된 회사', on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.company', verbose_name='회사'),
        ),
    ]
