# Generated by Django 5.2.8 on 2026-03-18 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0015_remove_artist_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_memos', to='performance.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '마케팅 메모',
                'verbose_name_plural': '마케팅 메모들',
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
